### ISSUE TITLE
Нет доступа к корзине в яндекс диске. Windows 11

### ISSUE THREAD

**Issue by gegemon2012** [ZZZConsulting/WebDavMailRuCloud#2]
Здравствуйте!
Использую это - WebDAVCloudMailRu-1.14.2.1-dotNet7Win.zip 
Установил службу - "C:\Users\User\WebDAVCloudMailRu\wdmrc.exe" --port "34111,41333" --install WebDavService
поключаюсь к яндекс диску:
net use Y: /DELETE
net use Y: http://127.0.0.1:41333 "пароль от учетной записи" /USER:логин@yandex.ru /persistent:no
pause

Диск подключается. На него через проводник виндоус можно копировать но удалять не дает. Удаляется только если зайти через браузер. 
Что я делаю не так?

**Comment by gegemon2012** [comment]
Использую файл *.cmd для подключения. Если запускаю его как администратор то ничего не происходит. Если просто запускаю то происходит подключение.

**Comment by ZZZConsulting** [comment]
Если здесь речь про Корзину на Диске Яндекса, то эмулятор WebDAVCloudMailRu содержимое корзины, как папки, никогда не показывал. По крайней мере, мне такое не известно. Если файл удаляется с Диска через эмулятор, то файл уходит в Корзину, а там этот файл удалить возможно только через веб-интерфейс Диска, либо через приложения от Яндекса.
У эмулятора есть набор команд, которыми, в частности, можно очистить корзину, но работать такие команды не будут при подключении диска через net use, нужно использовать более специфические приложения, например, плагин для работы с WebDav в Far Manager или Total Commander.

Чем отличается запуск батника с административными правами и без них, сказать сложно - надо смотреть. Если еще актуально - пишите, будем разбираться. Я бы вместо прямого подключения через net use рекомендовал какую-нибудь программу использовать, тот же RaiDrive, к примеру.

Обратил внимание на порт - "34111,41333".
Я совсем недавно где-то на просторах интернета обнаружил рекомендацию использовать по одному порту на одну учетную запись, по принципу - нужно столько портов, сколько будет учетных записей разных.
Не нужно!
В последних версиях эмулятора, все прекрасно работает с одним портом, и Яндекс, и Mail.ru, и любое количество учетных записей.
У меня одновременно 3 учетных записи Диска прекрасно работали через RaiDrive (я просто не использую подключение через net use - у Windows клиент WebDav убогий).
Ну, то есть, если два порта нужны - не вопрос, но обязательности в этом нет, можно на один все вешать. Главное чтобы порт был выше 1024, на низкие можно только с административными правами вешать прослушку.

**Comment by gegemon2012** [comment]
Да что тут актуального... С Яндексом вообще перестало работать. Попробую с одним портом и поменяю его заодно. Вдруг поможет. Посмотрел RaiDrive, но мне нужна запись на диск а этот функционал является платным. Поищу что-нибудь другое. В любом случае спасибо что ответили!

**Comment by ZZZConsulting** [comment]
Что-то на Вас осеняя хандра раньше времени напала. Выше голову!
Для RaiDrive не только не нужен вариант подключения к Яндекс, который платный, но он, по большому счету, вреден.
В RaiDrive нужно выбирать WebDav, и уже в нем настраивать сервер=127.0.0.1, порт и т.д. И только в таком случае с Диском работа будет через эмулятор. Берите последнюю версию и пробуйте настроить по инструкции. В варианте с BrowserAuthenticator должно работать. Надо только настроить все правильно.
